name: car_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.2
  dio: ^5.4.2+1
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  shoko_ui: ^0.0.14
  yandex_mapkit: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/auth_screen/backImage.png
  - assets/auth_screen/carIcon.png

  - assets/bottom_nav_bar/car.png
  - assets/bottom_nav_bar/like.png
  - assets/bottom_nav_bar/user.png
  - assets/bottom_nav_bar/plus.png
  - assets/bottom_nav_bar/chat.png

  - assets/user_screen/userPh.png
  - assets/user_screen/userChat.png
  - assets/user_screen/userHome.png
  - assets/user_screen/userInf.png
  - assets/user_screen/userStat.png
  - assets/user_screen/userTime.png
  - assets/user_screen/userBack.png

  - assets/home_screen/listIcon.png
  - assets/home_screen/mapIcon.png
  - assets/home_screen/toyota.png

  